name: CI

on:
  push:
    branches:
      - main

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings
  MSRV: "1.70"

jobs:
  build_binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: build release
        run: |
          cargo build --release
      
      - name: Setup awscli on linux
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
    
      - name: Set aws credentials
        run: |
            echo "AWS_ACCESS_KEY_ID=${{secrets.S3_ACCESS_KEY_ID}}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{secrets.S3_ACCESS_KEY}}" >> $GITHUB_ENV
            echo "AWS_DEFAULT_REGION=us-west-2" >> $GITHUB_ENV
      
      - name: push release
        run: |
          aws s3 cp ./target/release/metrics_exporter s3://vorc/metrics_exporter-linux-amd64-${GITHUB_SHA::7} --no-progress

      - name: push release latest
        run: |
          aws s3 cp ./target/release/metrics_exporter s3://vorc/metrics_exporter-linux-amd64-latest --no-progress